# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("calc.proto", :syntax => :proto3) do
    add_message "pb.CalcRequest" do
      optional :number_a, :int32, 1
      optional :number_b, :int32, 2
    end
    add_message "pb.CalcReply" do
      optional :result, :int32, 1
    end
  end
end

module Pb
  CalcRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.CalcRequest").msgclass
  CalcReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.CalcReply").msgclass
end
